import Head from 'next/head'
import { Inter } from '@next/font/google'
import { client } from "@/libs/client";
import 'bootstrap/dist/css/bootstrap.min.css'
import Container from 'react-bootstrap/Container'
import Nav from 'react-bootstrap/Nav'
import Navbar from 'react-bootstrap/Navbar'
import { Card, ListGroup } from 'react-bootstrap';

const inter = Inter({ subsets: ['latin'] })

export const getStaticProps = async() => {
  const data = await client.get({ endpoint: "news" });
  const createDate = data.contents.map((content) => 
    new Date(Date.parse(content.publishedAt)+32400000)
    .toLocaleDateString('ja-JP')
    .replace(/\//g, '/')
  );

  return {
    props: {
      news: data.contents,
      createDate,
    },
  };
};

export default function Home({ news, createDate }) {
  var i = 0;
  return (
    <>
      <Head>
        <title>beauty salon site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar variant="dark" collapseOnSelect expand="lg" fixed="top">
        <Container>
          <Navbar.Brand href="#home">beauty salon</Navbar.Brand>
          <Navbar.Toggle aria-controls="basic-navbar-nav" />
          <Navbar.Collapse id="basic-navbar-nav">
            <Nav className="ms-auto">
              <Nav.Link href="#news" className="px-3">News</Nav.Link>
              <Nav.Link href="#menu" className="px-3">Menu</Nav.Link>
              <Nav.Link href="#catalog" className="px-3">Catalog</Nav.Link>
              <Nav.Link href="#staff" className="px-3">Staff</Nav.Link>
              <Nav.Link href="#reserve" className="px-3">Reserve</Nav.Link>
              <Nav.Link href="#access" className="px-3">Access</Nav.Link>
            </Nav>
            <div className="ps-5 text-end">
              <a className="tel" href="tel:000-000-0000">000-000-0000</a>
              <span className="d-block hours">OPEN 9:30-20:00</span>
            </div>
          </Navbar.Collapse>
        </Container>
      </Navbar>
      <header className="header-img" id="home">
        <div className="vh-100 text-center text-white d-flex">
          <div className="container my-auto">
            <p className="top-message">Welcome page.</p>
            <p className="lead m-5">
              This page is sample.
            </p>
            <p className="lead">
              <a className="btn btn-success p-3 text-white" href="#reserve">
                Make reservation
              </a>
            </p>
          </div>
        </div>
      </header>
      <main>
        <div className="max-vh-100 py-5 text-center" id="news">
          <h1 className="py-5 fw-bold">NEWS</h1>
          <ul className="list-group news-w mx-auto pb-5">
            { news.map((news) => (
              <a key={news.id} href={`news/${news.id}`} className="list-group-item list-group-item-action list d-flex justify-content-between">
                <div>{news.title}</div>
                <div>{createDate[i++]}</div>
              </a>
            ))}
          </ul>
        </div>
        <div className="py-5 text-center text-white bg-secondary" id="menu">
          <h1 className="py-5 fw-bold">MENU</h1>
          <div className="d-lg-flex mx-auto pb-5 menu-w">
            <div className="list-w">
              <h2 className="pb-3 fw-bold">CUT</h2>
              <ListGroup variant="flush" className="bg-none">
                <ListGroup.Item className="d-flex justify-content-between bg-none">
                  <p>カット</p>
                  <p>¥4000</p>
                </ListGroup.Item>
                <ListGroup.Item  className="d-flex justify-content-between">
                  <p>スクールカット</p>
                  <p>¥3500</p>
                </ListGroup.Item>
              </ListGroup>
            </div>
            <div className="list-w">
              <h2 className="pb-3 fw-bold">COLOR</h2>
              <ListGroup variant="flush">
                <ListGroup.Item className="d-flex justify-content-between">
                  <p>シングルカラー</p>
                  <p>¥4000</p>
                </ListGroup.Item>
                <ListGroup.Item  className="d-flex justify-content-between">
                  <p>イルミナカラー</p>
                  <p>¥3500</p>
                </ListGroup.Item>
                <ListGroup.Item  className="d-flex justify-content-between">
                  <p>オーガニックカラー</p>
                  <p>¥3500</p>
                </ListGroup.Item>
                <ListGroup.Item  className="d-flex justify-content-between">
                  <p>バレイヤージュカラー</p>
                  <p>¥3500</p>
                </ListGroup.Item>
                <ListGroup.Item  className="d-flex justify-content-between">
                  <p>ホイルウィービング５枚~</p>
                  <p>¥3500</p>
                </ListGroup.Item>
                <ListGroup.Item  className="d-flex justify-content-between">
                  <p>グラデーションカラー</p>
                  <p>¥3500</p>
                </ListGroup.Item>
              </ListGroup>
            </div>
            <div className="list-w">
              <h2 className="pb-3 fw-bold">PERM</h2>
              <ListGroup variant="flush">
                <ListGroup.Item className="d-flex justify-content-between">
                  <p>ナチュラルウェーブ</p>
                  <p>¥4000</p>
                </ListGroup.Item>
                <ListGroup.Item  className="d-flex justify-content-between">
                  <p>デジタルパーマ</p>
                  <p>¥3500</p>
                </ListGroup.Item>
              </ListGroup>
            </div>
          </div>
          
        </div>
        <div className="min-vh-100 py-5 text-center bg-dark" id="catalog">
          <h1 className="py-5 fw-bold text-white">CATALOG</h1>
          <div className="d-lg-flex mx-auto catalog-w">
            <Card>
              <Card.Img variant="top" src="/catalog-sample.jpg/" />
              <Card.Body>
                <Card.Title>Card Title</Card.Title>
                <Card.Text>
                  Some quick example text to build on the card title and make up the
                  bulk of the card's content.
                </Card.Text>
              </Card.Body>
            </Card>
            <Card>
              <Card.Img variant="top" src="/catalog-sample2.jpg/" />
              <Card.Body>
                <Card.Title>Card Title</Card.Title>
                <Card.Text>
                  Some quick example text to build on the card title and make up the
                  bulk of the card's content.
                </Card.Text>
              </Card.Body>
            </Card>
            <Card>
              <Card.Img variant="top" src="/catalog-sample3.jpg/" />
              <Card.Body>
                <Card.Title>Card Title</Card.Title>
                <Card.Text>
                  Some quick example text to build on the card title and make up the
                  bulk of the card's content.
                </Card.Text>
              </Card.Body>
            </Card>
          </div>
          <a className="btn btn-success p-3 my-5 text-white" href="#reserve">
            View More
          </a>
        </div>
        <div className="vh-100 bg-secondary" id="staff">
          
        </div>
        <div className="vh-100" id="reserve">
          
        </div>
        <div className="vh-100 bg-info" id="access">
          
        </div>
      </main>
      <footer>
        
      </footer>

    </>
  )
}
