import Head from 'next/head'
import { Inter } from '@next/font/google'
import { client } from "@/libs/client";
import 'bootstrap/dist/css/bootstrap.min.css'
import Container from 'react-bootstrap/Container'
import Nav from 'react-bootstrap/Nav'
import Navbar from 'react-bootstrap/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const getStaticProps = async() => {
  const data = await client.get({ endpoint: "news" });
  const createDate = data.contents.map((content) => 
    new Date(Date.parse(content.publishedAt)+32400000)
    .toLocaleDateString('ja-JP')
    .replace(/\//g, '/')
  );

  return {
    props: {
      news: data.contents,
      createDate,
    },
  };
};

export default function Home({ news, createDate }) {
  var i = 0;
  return (
    <>
      <Head>
        <title>beauty salon site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar variant="dark" collapseOnSelect expand="lg" fixed="top">
        <Container>
          <Navbar.Brand href="#home">beauty salon</Navbar.Brand>
          <Navbar.Toggle aria-controls="basic-navbar-nav" />
          <Navbar.Collapse id="basic-navbar-nav">
            <Nav className="ms-auto">
              <Nav.Link href="#news" className="px-3">News</Nav.Link>
              <Nav.Link href="#menu" className="px-3">Menu</Nav.Link>
              <Nav.Link href="#catalog" className="px-3">Catalog</Nav.Link>
              <Nav.Link href="#staff" className="px-3">Staff</Nav.Link>
              <Nav.Link href="#reserve" className="px-3">Reserve</Nav.Link>
              <Nav.Link href="#access" className="px-3">Access</Nav.Link>
            </Nav>
            <div className="ps-5 text-end">
              <a className="tel" href="tel:000-000-0000">000-000-0000</a>
              <span className="d-block hours">OPEN 9:30-20:00</span>
            </div>
          </Navbar.Collapse>
        </Container>
      </Navbar>
      <header className="header-img" id="home">
        <div className="vh-100 text-center text-white d-flex">
          <div className="container my-auto">
            <p className="top-message">Welcome page.</p>
            <p className="lead m-5">
              This page is sample.
            </p>
            <p className="lead">
              <a className="btn btn-success p-3 text-white" href="#reserve">
                Make reservation
              </a>
            </p>
          </div>
        </div>
      </header>
      <main>
        <div className="vh-100 pt-5 text-center" id="news">
          <h1 className="py-5">NEWS</h1>
          <ul className="list-group">
            { news.map((news) => (
              <a key={news.id} href={`news/${news.id}`} className="list-group-item list-group-item-action list d-flex justify-content-between">
                <div>{news.title}</div>
                <div>{createDate[i++]}</div>
              </a>
            ))}
          </ul>
        </div>
        <div className="vh-100 bg-primary" id="menu">
          
        </div>
        <div className="vh-100 bg-secondary" id="catalog">
          
        </div>
        <div className="vh-100 bg-success" id="staff">
          
        </div>
        <div className="vh-100 bg-warning" id="reserve">
          
        </div>
        <div className="vh-100 bg-info" id="access">
          
        </div>
      </main>
      <footer>
        
      </footer>

    </>
  )
}
